import errors
import unittest

class TestTestError(unittest.TestCase):
    # TODO implement constructor tester
    def testInit(self):
        pass
